### ISSUE TITLE
ElementFactory needs explicit initialization when used through o.m.a.eclipse plugin

### ISSUE THREAD

**Issue by JoriDubrovin** [ModelDriven/Alf-Reference-Implementation#13]
Apparently, you need an explicit `new org.modeldriven.alf.eclipse.uml.ElementFactory();` before using the functionality of org.modeldriven.alf.eclipse, otherwise you get NPEs.  This is a minor nuisance.

Using [v0.6.0g](https://github.com/ModelDriven/Alf-Reference-Implementation/releases/tag/v0.6.0g).

**Comment by seidewitz** [comment]
This is due to a change made in order to avoid redundant instantiation of element factories. The ElementFactory constructor call is handled automatically when you instantiate an AlfCompiler. Nevertheless, the new approach is still probably not the best way to do this. There is a better alternative that avoids the redundancy but also does not require an explicit constructor call.

**Comment by seidewitz** [comment]
It is now unnecessary to explicitly call the ElementFactory constructor, as before. Indeed, there is now no org.modeldriven.alf.eclipse.uml.ElementFactory() constructor at all. If an element factory reference is needed, use org.modeldriven.alf.eclipse.uml.Element.FACTORY.

**Comment by JoriDubrovin** [comment]
[v0.6.0h](https://github.com/ModelDriven/Alf-Reference-Implementation/releases/tag/v0.6.0h) works for us without the explicit initialization step.

**Comment by seidewitz** [comment]
Resolved in v0.6.0h.
